### ISSUE TITLE
New articles are not searchable on the How-To site

### ISSUE THREAD

**Issue by ReneeRendon** [deconst/content-service#109]
New articles are not appearing in the search results on the How-To site.

(This was part of Issue #91  : Search issues on How-To site)

**Comment by ktbartholomew** [comment]
How old are the articles that aren't appearing? Google can take a few days to index new content before it appears in searches.

**Comment by ReneeRendon** [comment]
This article was merged 19 days ago, but does not show up in the search results. https://github.com/rackerlabs/rackspace-how-to/blob/master/content/cloud-servers/upgrade-citrix-tools-for-windows-servers.md

**Comment by narcher7** [comment]
Actually I did find the article by searching "Citrix Tools." The article we deleted today however, https://github.com/rackerlabs/rackspace-how-to/pull/831, still appears in search. Will this also take several days, or do we need to use the Google tools to remove the article entirely?

**Comment by ReneeRendon** [comment]
Woot! I finally appears! Thanks for checking it Nate.

The deleted one was deleted less than an hour ago, so it still needs time.

**Comment by ReneeRendon** [comment]
As a test, we can see how long it takes this to appear in the search results. This was merged several minutes ago. 
https://github.com/rackerlabs/rackspace-how-to/blob/master/content/cloud-databases/Replicate-backup-for-disaster-recovery-with-cloud-databases.md

**Comment by ReneeRendon** [comment]
I am closing this issue. Now that we can access the Google Search Console, the How-To team will work on the fix.
