### ISSUE TITLE
Expire staging content

### ISSUE THREAD

**Issue by smashwilson** [deconst/content-service#87]
Content pushed to the staging server sticks around forever. I expect it to pile up much more quickly than production content, though, because we get a set of metadata envelopes for each commit on each pull request. It would be a good idea to provide some strategy for gradually removing content.

The easiest thing to do would be to expire content in Cloud Files after a certain number of days. There may be a way to tie the lifespan of an envelope to the originating pull request, but that would be more difficult.

**Comment by nimbinatus** [comment]
As deconst content is backed by Mongo, the easiest thing, I think, would be to use Mongo's [TTL](https://docs.mongodb.com/manual/tutorial/expire-data/) option and bake it into the current structure of the database. Only work needed might be to ensure the TTL setup goes live when a new database is spun up, so need to check with [deconst/deploy](https://github.com/deconst/deploy/) to see if anything needs to be done with `script/up`. Probably going to set the expiration on default at 30 days.
