### ISSUE TITLE
Search issues on How-To site

### ISSUE THREAD

**Issue by ReneeRendon** [deconst/content-service#91]
The search ability on the How-To site has some major issues. The three issues that need to be resolved are below:
- Articles that have been deleted still appear in the search results.
- New articles are not appearing in the search results.
- The search results repeat itself instead having an end to the list.

**Comment by kenperkins** [comment]
I think the big elephant in the room is whether or not we should continue to use Google Site-Search for the How-To.

**Comment by ktbartholomew** [comment]
I think for the same reasons it made sense to migrate the how-to to a platform we're already using elsewhere in nexus, it also would also make sense to consolidate the search so all three of our major sites use the same tooling. Deconst's search isn't without its own issues, but at least then we'll be solving problems for all three sites at once.

There's a bit more of an engineering lift to get the search components into the how-to site, as I'll have to learn how all their front-end code was organized.

**Comment by kenperkins** [comment]
Which begs the question: should the front-end of the how-to be redone to match the architecture of our other sites? :smile:

**Comment by ktbartholomew** [comment]
plz no

**Comment by ktbartholomew** [comment]
Received an update from Chad Pritchett in NebOps about this:

> Hi Keith,
> 
> The indexing issue there is likely due to licensing.  We’re working on getting that resolved and we’ll keep you updated.

**Comment by ktbartholomew** [comment]
It looks like a malformed sitemap had been submitted to Google when the site was first created, which was preventing Google from adding newly indexed content to the list of results. The one specific query I've been following is for "server security", which had been returning a very old version of the first article in the results list. It's now reflecting an update that was made last week or so.

@ReneeRendon you'll be more equipped to do an audit of the results. If they seem to be generally on track, we can close this issue and open up new ones if more specific problems pop up.

**Comment by stephamon** [comment]
@ktbartholomew the search results don't appear to be repeating anymore after clicking on "More results" a few times, but I did check to see if some articles I deleted this week were still viewable in the search results, and they're still there.

Search for "cloudfuse" (an article on which I removed yesterday or the day before) and it's the first link in the search results.

**Comment by ktbartholomew** [comment]
@stephamon could you try that same test with changes you made _last week_? Google's reindexing can be a little slow.

**Comment by stephamon** [comment]
@ktbartholomew Yeah, still there. I removed the "Cloud Backup Overview" article 9 days ago and it still shows up in the search results.

**Comment by ktbartholomew** [comment]
@stephamon since deleted content is kind of a special case, could you check for articles that have _changed_ recently? The way I was doing this test was by checking to see if the date in the search preview matches that of the most recent update. Again, changes made within the past few days may not have appeared yet.

**Comment by stephamon** [comment]
@ktbartholomew Content updated last week has the right updated date in the search, but content updated this week does not.

**Comment by ktbartholomew** [comment]
That sounds about right!

**Comment by ReneeRendon** [comment]
The only item that seems to be fixed in this issue is the last bulleted item about the repeating results. New articles are not showing up and deleted articles are not going away.
